version: '3.8'

services:
  # Usager Service
  usager-service:
    build: ./microservices/usager-service
    container_name: dgtt-usager-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-usager:5432/usager_db
      - SPRING_DATASOURCE_USERNAME=dgtt_user
      - SPRING_DATASOURCE_PASSWORD=dgtt_password_123
    depends_on:
      - postgres-usager
    networks:
      - dgtt-network

  # Usager Database
  postgres-usager:
    image: postgres:15-alpine
    container_name: dgtt-postgres-usager
    restart: unless-stopped
    environment:
      - POSTGRES_DB=usager_db
      - POSTGRES_USER=dgtt_user
      - POSTGRES_PASSWORD=dgtt_password_123
    volumes:
      - postgres_usager_data:/var/lib/postgresql/data
      - ./databases/init/usager.sql:/docker-entrypoint-initdb.d/usager.sql:ro
    ports:
      - "5432:5432"
    networks:
      - dgtt-network

  # Traefik API Gateway
  traefik:
    image: traefik:v2.10
    container_name: dgtt-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik/dynamic:/etc/traefik/dynamic:ro
    environment:
      - TRAEFIK_LOG_LEVEL=INFO
    networks:
      - dgtt-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

  # Consul Service Discovery
  consul:
    image: consul:1.16
    container_name: dgtt-consul
    restart: unless-stopped
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - CONSUL_CLIENT_INTERFACE=eth0
    command: >
      consul agent
      -server
      -bootstrap-expect=1
      -ui
      -client=0.0.0.0
      -bind=0.0.0.0
      -retry-join=consul
      -data-dir=/consul/data
      -datacenter=dgtt-datacenter
      -node=dgtt-consul-1
    volumes:
      - consul-data:/consul/data
      - ./config/consul:/consul/config:ro
    networks:
      - dgtt-network

volumes:
  postgres_usager_data:
  consul-data:

networks:
  dgtt-network:
    driver: bridge
